#!url=https://raw.githubusercontent.com/anpplex/Surge/main/sgmodule/NotabilityPlusUnlock.module
#!name=Notability Plus

#!desc=Notability解锁

#!author=anpple



[MITM]

hostname = %APPEND% notability.com



[Script]

Notability Plus=type=http-response,pattern=^https://notability.com/(global|subscriptions),requires-body=1,script-path=https://raw.githubusercontent.com/anpplex/Surge/main/Script/notability.js
